### ISSUE TITLE
Gun Reload Icon Issue

### ISSUE THREAD

**Issue by Ocelot5836** [MrCrayfish/MrCrayfishGunMod#7]
When you fire a gun, it draws a cooldown bar over all GUIS. So if you open your inventory or open a chest after firing a gun, you can still see it.

**Comment by MrCrayfish** [comment]
Fixed in some random commit ages ago

**Comment by Ch1216** [comment]
This issue is back again,
also kind of related, when you tab out the cooldown disappears (in gui or not)
Might make another issue
